name: "goast"
description: "Runs goast as GitHub action for customizable static analysis of Go code"
inputs:
  policy:
    description: "Rego policy file or directory"
    required: true
  format:
    description: "Output format [text|json]"
    default: "text"
  output:
    description: "Output destination"
    default: "-"
  root_only:
    description: "Disable recursive inspection of all AST nodes"
    default: "false"
  fail:
    description: "Exit with non-zero if violation detected"
    default: "true"
  source:
    description: "Source code files or directory"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - eval
    - --policy=${{ inputs.policy }}
    - --format=${{ inputs.format }}
    - --output=${{ inputs.output }}
    - --root-only=${{ inputs.root_only }}
    - --fail=${{ inputs.fail }}
    - ${{ inputs.source }}
